const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DATABASE_URL,
  CHANNEL,
  HEARTBEAT,
  SENTENCE_TIMEOUT,
  PICTURE_TIMEOUT,
  GAME_TIMEOUT,
  MINIMUM_TURN_COUNT,
} = Bun.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !DATABASE_URL || !CHANNEL) {
  throw new Error("Missing environment variables");
}

export default {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DATABASE_URL,
  CHANNEL,
  SENTENCE_TIMEOUT: SENTENCE_TIMEOUT && parseInt(SENTENCE_TIMEOUT) || 60 * 10,
  PICTURE_TIMEOUT: PICTURE_TIMEOUT && parseInt(PICTURE_TIMEOUT) || 60 * 60 * 24,
  GAME_TIMEOUT: GAME_TIMEOUT && parseInt(GAME_TIMEOUT) || 60 * 60 * 24 * 7,
  // Games can't end unless they have at least this many turns
  MINIMUM_TURN_COUNT: MINIMUM_TURN_COUNT && parseInt(MINIMUM_TURN_COUNT) || 3,
  HEARTBEAT: HEARTBEAT && parseInt(HEARTBEAT) || 60,
  
};