const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  SENTENCE_TIMEOUT,
  PICTURE_TIMEOUT,
  GAME_TIMEOUT,
  HEARTBEAT,
  DATABASE_URL,
  CHANNEL,
  PICTURE_WIDTH,
  PICTURE_HEIGHT,
} = Bun.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID) {
  throw new Error("Missing environment variables");
}

export default {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  SENTENCE_TIMEOUT: SENTENCE_TIMEOUT && parseInt(SENTENCE_TIMEOUT) || 60 * 10,
  PICTURE_TIMEOUT: PICTURE_TIMEOUT && parseInt(PICTURE_TIMEOUT) || 60 * 60 * 24,
  GAME_TIMEOUT: GAME_TIMEOUT && parseInt(GAME_TIMEOUT) || 60 * 60 * 24 * 7,
  HEARTBEAT: HEARTBEAT && parseInt(HEARTBEAT) || 60,
  DATABASE_URL,
  CHANNEL,
  PICTURE_WIDTH: PICTURE_WIDTH && parseInt(PICTURE_WIDTH) || 50,
  PICTURE_HEIGHT: PICTURE_HEIGHT && parseInt(PICTURE_HEIGHT) || 50,
};